//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"math"
	"os"

	"github.com/apparentlymart/go-textseg/v16/textseg/internal/charprops/gentable"
)

func main() {
	tree, err := gentable.BuildRawPropertyTree("ucd")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Generated by generate.go. DO NOT EDIT!")
	fmt.Fprintln(&buf, "")
	fmt.Fprintln(&buf, "package charprops")
	fmt.Fprintln(&buf, "")

	// The tree builder uses uint16 for the indices because in theory we could
	// need that in future, but currently the tree is small enough that
	// uint8 is actually sufficient and so we'll use that for now to avoid
	// redundantly storing a bunch of zeroes.
	fmt.Fprintln(&buf, "var lookupIndices = [...]uint8{")
	for i := 0; i < len(tree.Indices); i += 8 {
		items := tree.Indices[i:]
		items = items[:min(len(items), 8)]
		fmt.Fprint(&buf, "\t")
		for _, v := range items {
			if v > math.MaxUint8 {
				panic("too many indices to use uint8")
			}
			fmt.Fprintf(&buf, "0x%02x,", v)
		}
		fmt.Fprint(&buf, "\n")
	}
	fmt.Fprintln(&buf, "}")

	fmt.Fprintln(&buf, "var lookupProps = [...]CharProperties{")
	for i := 0; i < len(tree.Properties); i += 8 {
		items := tree.Properties[i:]
		items = items[:min(len(items), 8)]
		fmt.Fprint(&buf, "\t")
		for _, v := range items {
			fmt.Fprintf(&buf, "0x%02x,", v)
		}
		fmt.Fprint(&buf, "\n")
	}
	fmt.Fprintln(&buf, "}")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}

	f, err := os.Create("property_table_raw.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}
	f.Write(src)
}
