language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x

env:
  GO111MODULE=on

matrix:
  fast_finish: true

before_install:
  - go get -t -v ./...

script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./textseg
  - cd autoversion && go test ./textseg

after_success:
  - bash <(curl -s https://codecov.io/bash)
